### ISSUE TITLE
OSError when script runs DocScriptUtil 

### ISSUE THREAD

**Issue by colematt** [broadwaylamb/generate-llvm-docset#2]
### Minimally Reproducible Error

```shell
$ gh repo clone broadwaylamb/generate-llvm-docset && cd generate-llvm-docset
$ mkdir build && cd build
$ ../generate-llvm-docset.py 10.0.0
Downloading llvm-10.0.0.src.tar.xz from https://github.com/llvm/llvm-project/releases/download/llvmorg-10.0.0/llvm-10.0.0.src.tar.xz...
Extracting llvm-10.0.0.src.tar.xz into llvm-10.0.0.src...
Configuring doxygen using llvm-10.0.0.src/docs/doxygen.cfg.in...
Generating HTML documentation (this may take some time)...
Running /usr/bin/doxygen doxygen.cfg
Creating LLVM.docset (this may take some time)...
Running ../DocSetUtil/Developer/usr/bin/docsetutil index LLVM.docset
Traceback (most recent call last):
  File "../generate-llvm-docset.py", line 577, in <module>
    generator.run()
  File "../generate-llvm-docset.py", line 484, in run
    docset = self.generate_docset_from_html(html_docs)
  File "../generate-llvm-docset.py", line 401, in generate_docset_from_html
    self.__run_docsetutil(docset)
  File "../generate-llvm-docset.py", line 324, in __run_docsetutil
    process = subprocess.Popen(command, stdout=subprocess.PIPE)
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '../DocSetUtil/Developer/usr/bin/docsetutil'
```

### Environment 

- `/usr/bin/env python3 --version` is `Python 3.8.5`. 
- `which doxygen` is `/usr/bin/doxygen`, version 1.8.17
- `which dot` is `/usr/bin/dot`, graphviz version 2.43.0 (0)
- Both generate-llvm-docset.py and ./DocSetUtil/Developer/usr/bin/docsetutil are executable. 
- I am using PopOS 20.10 Linux, a Ubuntu derivative based on Ubuntu 20.10.

**Comment by broadwaylamb** [comment]
Sorry, this script only works on macOS.

**Comment by colematt** [comment]
Ah, I see that `file ./DocSetUtil/Developer/usr/bin/docsetutil` is a Mach-O 64 bit executable. So if there was a ELF docsetutil, the script should work otherwise, right?

**Comment by broadwaylamb** [comment]
Yep. But DocSetUtil is an Apple's tool, so there is no ELF equivalent for it.

Although, creating a similar cross-platform tool would be pretty straightforward. I just didn't have time to do it.

**Comment by colematt** [comment]
OK. I'll take that on for a possible future work. I'm a little busy preparing academic papers to do it now. Anyways, I have an older Mac here in the lab I can let run for a while to generate the docset then thumbdrive it over to the Linux machine so that Zeal (the Linux clone of Dash) can use it. Closing this issue for now, will open a pull request when I'm ready. Thanks!
